name: verymemo
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 상태관리 (riverpod)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Http Client
  dio: ^5.7.0

  # Retrofit
  retrofit: '>=4.0.0 <5.0.0'

  # Firebase 인증
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2

  # Google Drive 연동
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  url_launcher: ^6.3.1

  # 모델 생성 (Freezed)
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  # 라우터 (Go Router)
  go_router: '>=14.0.0 < 16.0.0'

  # 권한 관리 (Permission)
  permission_handler: ^11.3.1

  # Shared Preference
  shared_preferences: ^2.3.4

  # isar - db
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # 스플래시
  flutter_native_splash: ^2.4.3

  # 네트워크 상태관리
  connectivity_plus: ^6.1.1

  # Utils - 파일 경로
  path: ^1.9.0
  path_provider: ^2.1.5

  # Utils - 이미지
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  lottie: ^3.2.0
  image_picker: ^1.1.2

  # Utils - 토스트
  fluttertoast: ^8.2.10

  # Utils - 페이지 인디게이터
  smooth_page_indicator: ^1.2.0+3

  # Utiils - 포매터
  intl: ^0.19.0

  # Utils - Device Info
  device_info_plus: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  go_router_builder: ^2.7.1
  retrofit_generator: '>=8.0.0 <10.0.0'

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
