import 'package:flutter/material.dart';
import 'package:verymemo/core/styles/app_color.dart';

ColorScheme lightThemeColors(context) {
  return const ColorScheme(
    brightness: Brightness.light,
    primary: AppColor.coral,
    onPrimary: AppColor.white,
    primaryContainer: AppColor.palepink,
    onPrimaryContainer: AppColor.coral,
    secondary: AppColor.purple,
    onSecondary: AppColor.white,
    secondaryContainer: AppColor.palepurple,
    tertiary: AppColor.palegrey,
    onTertiary: AppColor.grey60,
    tertiaryContainer: AppColor.palegrey,
    onTertiaryContainer: AppColor.grey30,
    error: AppColor.red,
    onError: AppColor.white,
    onErrorContainer: AppColor.redbrown,
    surfaceDim: AppColor.hover,
    surface: AppColor.white,
    surfaceBright: AppColor.grey0,
    surfaceContainerLowest: AppColor.grey20,
    surfaceContainerLow: AppColor.grey40,
    surfaceContainer: AppColor.grey80,
    surfaceContainerHigh: AppColor.grey90,
    surfaceContainerHighest: AppColor.grey100,
    onSurface: AppColor.grey70,
    onSurfaceVariant: AppColor.grey50,
    outline: AppColor.grey5,
    outlineVariant: AppColor.grey10,
    scrim: AppColor.modal,
    inverseSurface: AppColor.grey100,
    onInverseSurface: AppColor.white,
  );
}

ColorScheme darkThemeColors(context) {
  return const ColorScheme(
    brightness: Brightness.dark,
    primary: AppColor.coral,
    onPrimary: AppColor.white,
    primaryContainer: AppColor.grey60,
    onPrimaryContainer: AppColor.white,
    secondary: AppColor.purple,
    onSecondary: AppColor.white,
    secondaryContainer: AppColor.palepurple,
    tertiary: AppColor.grey80,
    onTertiary: AppColor.grey60,
    tertiaryContainer: AppColor.palegrey,
    onTertiaryContainer: AppColor.grey50,
    error: AppColor.red,
    onError: AppColor.white,
    onErrorContainer: AppColor.redbrown,
    surfaceDim: Color(0xff222222),
    surface: AppColor.grey100,
    surfaceBright: AppColor.grey80,
    surfaceContainerLowest: AppColor.grey60,
    surfaceContainerLow: AppColor.grey40,
    surfaceContainer: AppColor.grey5,
    surfaceContainerHigh: AppColor.grey0,
    surfaceContainerHighest: AppColor.grey100,
    onSurface: AppColor.grey10,
    onSurfaceVariant: AppColor.grey30,
    outline: AppColor.grey80,
    outlineVariant: AppColor.grey70,
    scrim: AppColor.modal,
    inverseSurface: AppColor.white,
    onInverseSurface: AppColor.grey100,
  );
}

TextTheme textTheme(context) => const TextTheme(
      displayLarge: TextStyle(
          fontSize: 56,
          fontWeight: FontWeight.w500,
          letterSpacing: -2.24,
          height: 1.2),
      displayMedium: TextStyle(
          fontSize: 46,
          fontWeight: FontWeight.w500,
          letterSpacing: -1.84,
          height: 1.2),
      displaySmall: TextStyle(
          fontSize: 36,
          fontWeight: FontWeight.w500,
          letterSpacing: -1.44,
          height: 1.2),
      headlineLarge: TextStyle(
          fontSize: 32,
          fontWeight: FontWeight.w500,
          letterSpacing: -0.64,
          height: 1.2),
      headlineMedium: TextStyle(
          fontSize: 28,
          fontWeight: FontWeight.w500,
          letterSpacing: -0.56,
          height: 1.2),
      headlineSmall: TextStyle(
          fontSize: 24,
          fontWeight: FontWeight.w500,
          letterSpacing: -0.48,
          height: 1.2),
      titleLarge: TextStyle(
          fontSize: 22,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.44,
          height: 1.4),
      titleMedium: TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.36,
          height: 1.4),
      titleSmall: TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.32,
          height: 1.4),
      labelLarge: TextStyle(
          fontSize: 15,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.15,
          height: 1.4),
      labelMedium: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.14,
          height: 1.4),
      labelSmall: TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.12,
          height: 1.4),
      bodyLarge: TextStyle(
          fontSize: 15,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.15,
          height: 1.6),
      bodyMedium: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.14,
          height: 1.6),
      bodySmall: TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: -0.12,
          height: 1.6),
    );
