// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mG__LH7za_g8ay54rfZQZOgi1SqMdYQ',
    appId: '1:634454835385:web:d06b8b120e337241619b68',
    messagingSenderId: '634454835385',
    projectId: 'very-memo',
    authDomain: 'very-memo.firebaseapp.com',
    storageBucket: 'very-memo.firebasestorage.app',
    measurementId: 'G-NVLZ4NMDV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwyAMazRe06EmNO8Ek2UcekUjOBhbb0zA',
    appId: '1:634454835385:android:b72f320db6dbdaa9619b68',
    messagingSenderId: '634454835385',
    projectId: 'very-memo',
    storageBucket: 'very-memo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACeAEzfW0FfljtYYc_C_I6sQM5OrxZixo',
    appId: '1:634454835385:ios:b44169da394eee5c619b68',
    messagingSenderId: '634454835385',
    projectId: 'very-memo',
    storageBucket: 'very-memo.firebasestorage.app',
    androidClientId:
        '634454835385-4qtnscbsm38bda7kgv611nvo6j91j9ph.apps.googleusercontent.com',
    iosClientId:
        '634454835385-bduobhit7vs66bdkqjca557fviul5v9q.apps.googleusercontent.com',
    iosBundleId: 'io.very.verymemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACeAEzfW0FfljtYYc_C_I6sQM5OrxZixo',
    appId: '1:634454835385:ios:b44169da394eee5c619b68',
    messagingSenderId: '634454835385',
    projectId: 'very-memo',
    storageBucket: 'very-memo.firebasestorage.app',
    androidClientId:
        '634454835385-4qtnscbsm38bda7kgv611nvo6j91j9ph.apps.googleusercontent.com',
    iosClientId:
        '634454835385-bduobhit7vs66bdkqjca557fviul5v9q.apps.googleusercontent.com',
    iosBundleId: 'io.very.verymemo',
  );
}
